### ISSUE TITLE
Question: acquisition of unit descriptions

### ISSUE THREAD

**Issue by jczaplew** [rclark/grand-canyon-geology#13]
Looking at the original sources of the data, it seems that the only resource that contains the detailed description of the map units is a PDF. Are these unit descriptions available somewhere as a table that can be joined to the original geometry?

Thanks! I love this map.

**Comment by rclark** [comment]
You can find a .csv file with all the descriptions from the map here: https://github.com/rclark/grand-canyon-geology/blob/gh-pages/data/all-units.csv. There's still a lot more work that could be done to clean this up and correlate units across map boundaries better.

**Comment by rclark** [comment]
See also https://github.com/rclark/grand-canyon-geology/issues/2

**Comment by jczaplew** [comment]
Does this CSV exist as a product from USGS, or was it manually constructed from the original PDF?

**Comment by rclark** [comment]
No, the CSV represents my attempt to harmonize the unit descriptions from a number of USGS publications that I drew on for the data themselves:

http://pubs.usgs.gov/imap/i2766
http://pubs.usgs.gov/imap/i-2688
http://pubs.usgs.gov/sim/2006/2895
http://pubs.usgs.gov/sim/2007/2977
http://pubs.usgs.gov/sim/2006/2900
http://pubs.er.usgs.gov/publication/sim3227

**Comment by aazaff** [comment]
Did this information ever make its way into Macrostrat?

@jczaplew
