### ISSUE TITLE
No legend, and clicking on formations no longer describes them

### ISSUE THREAD

**Issue by brandon-rhodes** [rclark/grand-canyon-geology#14]
Good morning!

I was writing an email to a friend describing where the Supergroup emerges near the base of the Tanner trail, and brought the map up for the first time in a month or two:

http://rclark.github.io/grand-canyon-geology/

I remember several weeks ago being able to click on geologic formations to see their names, but clicking no longer elicits any response from the map. I do see a few errors in the js console:

```
a.tiles.mapbox.com/v4/rclark.d2f57dc3/12/774/1608@2x.png?access_token=pk.eyJ1IjoicmNsYXJrIiwiYSI6IlQwaklqazAifQ.OWuTG3XPSdvoq_zGL0-1tA:1 GET http://a.tiles.mapbox.com/v4/rclark.d2f57dc3/12/774/1608@2x.png?access_token=pk.eyJ1IjoicmNsYXJrIiwiYSI6IlQwaklqazAifQ.OWuTG3XPSdvoq_zGL0-1tA 403 (Forbidden)
```

But as I wasn't viewing the js console before, I don't know whether those are new or not.

**Comment by brandon-rhodes** [comment]
If I create my own Mapbox account and substitute the API key into the two places in `gcg.js` where the old API key sits, then I can view the map locally — but the map layers still entirely load clicking.

On the other hand, if I view the polygon map layer directly at Mapbox with my own API key, then I can not only zoom but click on rock layers and see their description!

`http://a.tiles.mapbox.com/v4/rclark.h39e40a5/page.html?access_token=...`

But I can't work out why click aren't working any more in the app itself.

**Comment by rclark** [comment]
Yeah, not sure exactly what changed, but I think I got it back up and running now. If you can confirm on your side, I'll close here!

Thanks for the report!

**Comment by brandon-rhodes** [comment]
You did it! It works! Thanks so much, this is a great resource and I'm happy to see it continue to be maintained.
