### ISSUE TITLE
Can't see map anymore

### ISSUE THREAD

**Issue by ifollowzeehawk** [rclark/grand-canyon-geology#18]
Howdy!

I found this beautiful map from a link on the NPS website for the Canyon. It has been fun to look at, and useful for doing some preliminary scouting for a backpacking loop I am planning out for next year. Last week (~11/17/2020) I stopped being able to see the map on my Chrome browser (Version 87.0.4280.66 [(Official Build) (64-bit)]. The rock layer descriptions still appear when I hover over the blank map with my mouse, but I can no longer see anything where the map used to be, just blank space. I tried viewing the map using a Firefox browser [Firefox 82.0.3 (20201108180448) (64-bit)] and had the same result.

I can see you made this map quite a few years ago, so I definitely understand if you're not interested in returning to the project at this point, but I figured I would give you a head's up in case you've still got some interest in keeping it running (assuming it is not something on my end that is messing it up). Either way, I enjoyed my brief time with it in 2020, so thanks for developing this and providing it to the public!

Best wishes,
Eric

**Comment by rclark** [comment]
Oh my thank you for the notice. The map had a dependency on some code that's been deprecated. I'd done most of the work to fix it but I have been procrastinating the last steps. It looks like the deprecation has become a reality now, so I need to get this back together. Soon!

**Comment by rclark** [comment]
Should be back now. If you refresh your browser a couple of times and maybe wait a minute. Thanks again for the heads up.

**Comment by ifollowzeehawk** [comment]
Works great, thank you!
