### ISSUE TITLE
Feature request: display elevation as mouse moves?

### ISSUE THREAD

**Issue by brandon-rhodes** [rclark/grand-canyon-geology#20]
Following a corridor hike last weekend, I'm interested in plotting the elevation of the Canyon's layers along the length of the North Kaibab Trail. Currently the interactive geologic map requires me to find a marked elevation line, follow it over to the formation of interest, and then count up or down the contours to estimate the elevation at which two layers meet.

1. I suppose I should start by asking: is this map the wrong dataset if I want precise elevations, as opposed to knowing lateral extent? I have looked briefly for a stratigraphic profile of Bright Angel Canyon but have not yet found anything that's to scale and labeled with elevation.
2. Would it be possible for the corner of the map to display elevation as the mouse moves across its surface? Or would that require too much extra data to load, given the resource limits that the map currently operates under? (And perhaps also: would that necessarily match the contours, or do elevation data sets tend to diverge from visible contours because they use a grid of points, or triangles, instead of following contours like topographic maps do?)

Thanks for any thoughts on these questions!

**Comment by rclark** [comment]
To be blunt, yes, this map isn't great for getting precise elevations. 

What you need is a continuous dataset (raster) where each pixel represents the avg. elevation of a ~3x3m area. With that and the right software, you can find the elevation of any point under a cursor. Or, if you have a representation of the North Kaibab Trail as geojson, then you can use each of the vertices as a "cursor", extract the elevation value from the DEM and annotate each vertex with the elevation at that position. That gives you the cross-sectional view of the trail.

Lastly, various vector analysis software ought to be able to help you find the lat/lng position of intersections between the trail (a line in space) and any contour (another line in space). Tools like Turf are great for doing this in JS. Note that you can download all the contact lines for this map as GeoJSON.

As much as I like doing this kind of work, and would love to see it on a map on a website, its a pretty substantive effort and some of the quickest ways to get it done are via one-off scripts. Writing a generic tool, especially one that runs in a web browser, is quite a bit more challenging than I can commit to right now.

**Comment by brandon-rhodes** [comment]
> To be blunt, yes, this map isn't great for getting precise elevations.

Thanks! I agree that any effort on your part to provide elevations would be unreasonable for this map and this use case — your answer by itself is valuable and is what I needed: a confirmation of my own impression that this data set is inherently 2D, and that George didn’t encode explicit elevations as he defined the areas on his map that would be shaded with each rock layer.

I’ll clarify that I don’t just want the elevation of the trail itself and the rock layers on which it stands, but a diagram of the cliff walls above the trail showing, say, how the supergroup and Tapeats layers stand above the North Kaibab Trail as it winds north.

My guess is that counting contour lines is the right approach, and that I should do so using the printed geological map, as it will be there that the rock layer colors most closely correspond as he intended with the contour-lines of the Canyon. Assuming that I don't happen to find publications that provide the cross sections I'm interested in, that's the approach I will take.

Thanks again for weighing in!

**Comment by rclark** [comment]
Just for fun:

<img width="1857" alt="Screen Shot 2020-12-15 at 11 45 10 AM" src="https://user-images.githubusercontent.com/515424/102258273-9d62af80-3ec2-11eb-86ac-a2a997aad5e6.png">

**Comment by brandon-rhodes** [comment]
Wow, thanks for trying an actual overlay! I think it shows just what we feared: that what it real life might be a line of cliffs with a fairly straight bottom, might when drawn across the digital elevations wind up as a wavy line. So I will have to use photographs or, where they are lacking, outright guess about where a line Billingsley drew is intended to show a straight line between layers, and where he actually intends to show a more complicated interface between strata (or, a complicated shape made by a scree slope in front of a cliff).
