### ISSUE TITLE
Units missing descriptions or proper color

### ISSUE THREAD

**Issue by rclark** [rclark/grand-canyon-geology#25]
The map still lacks descriptions for units with the following labels.

- Tvi
- Ts1
- Ts2
- Trm
- Tg
- ^mss (^ means Triassic)
- ^mhm
- Qtg
- Qp
- Qao
- QTp
- QTb
- QTa

First step in tracking these down would be figuring out where on the map they appear.

**Comment by brandon-rhodes** [comment]
The group `Qtg` is on the right bank, around River Mile 125 (just before Fossil Rapids), and on both banks around Fishtail Rapids RM139. Let me know if I should track down the others, or if you'll simply generate local maps with only the layers in question to find them more quickly.

**Comment by rclark** [comment]
I'll see what I can do. But if you know any of these, just drop a comment here -- that's quite helpful.

**Comment by brandon-rhodes** [comment]
To follow up on that identification: the map at

https://pubs.usgs.gov/imap/i-2688/i-2688.pdf

shows **Qtg** as:

"Terrace gravel deposits (Holocene and Pleistocene)"

It's colored yellow with red dots.

I'll see if I can track down the others.

**Comment by brandon-rhodes** [comment]
My starting point for finding Grand Canyon geologic quadrangles:

https://azgs.arizona.edu/interactive-geologic-map-grand-canyon

I have identified the missing layers by shifting my map to black and white and then rendering each layer-of-interest in red, and then consulting the appropriate quads:

* **Tvi** — [Mount Trumbull quad](https://pubs.usgs.gov/imap/i2766/): a single collapse feature (the code is used for only one polygon) inside the area marked “THE GRAND PIPE”. Described as **Plug of The Grand Pipe** in the legend, under “Volcanic rocks of the Hualapai Plateau, undivided (Early to middle Miocene)”.
* **Ts1** — [Peach Springs quad](https://pubs.usgs.gov/sim/2006/2900/): large areas south of the river; described in the legend under “SEDIMENTARY ROCKS” as **Old gravel and sedimentary deposits (lower Miocene, Oligocene, Eocene, Paleocene, and Upper Cretaceous)**.
* **Ts2** — From the same quad, **Oldest gravel and sedimentary deposits (Paleocene(?) and Upper Cretaceous)**
* **Trm** — [Grand Canyon quadrangle](https://pubs.usgs.gov/imap/i-2688/): two small green areas southwest of Grand Canyon Village, beside the railroad and hard beside the Bright Angel Fault. Written on the map with “TR” as a single combined letter. The legend lists it under “MESOZOIC AND PALEOZOIC SEDIMENTARY ROCKS” as “Moenkopi Formation (Lower Triassic)”. ~**You can rename this** to `TRm` to correctly associate it with the same formation as pulled from other quads.~ (See next comment)
* **Tg** — [Peach Springs quad](https://pubs.usgs.gov/sim/2006/2900/): a few hundred yellow polygons south and west of the river’s final run to the northwest. Under “SURFICIAL DEPOSITS” listed as “Young gravel and sedimentary deposits (Pliocene to upper Miocene)”.
* **TRmhm** — [Cameron quad](https://pubs.usgs.gov/sim/2007/2977/): under the “Moenkopi Formation”, described as **Holbrook and Moqui Members, undivided (Middle(?) and Lower Triassic)**.
* **TRmss** — [Cameron quad](https://pubs.usgs.gov/sim/2007/2977/): under the “Moenkopi Formation”, described as **Shnabkaib Member and lower massive sandstone member, undivided (Lower Triassic)**.
* **Qtg** — (as mentioned in the comments above: “Terrace gravel deposits (Holocene and Pleistocene)”)
* **Qp** — **Pyroclastic deposits (Pleistocene)**
* **Qao** — [Mount Trumbull quad](https://pubs.usgs.gov/imap/i2766/): **Older alluvial fan deposits (Holocene(?) and Pleistocene)** in the northwest corner of the quad, out beyond the Grand Wash Cliffs, in a light peach color. Also smattered across a few of the southeast quads, far south of the Canyon itself.
* **QTp** — [Valle quad](https://pubs.usgs.gov/sim/2006/2895/): “VOLCANIC ROCKS” **Pyroclastic deposits (Pleistocene and Pliocene; Matuyama age)** in two spots near the lower right; more frequent across the [Cameron quad](https://pubs.usgs.gov/sim/2007/2977/) where it has the same description.
* **QTb** — [Cameron quad](https://pubs.usgs.gov/sim/2007/2977/) is where it primarily shows up: **Basalt flows (Pleistocene(?) or Pliocene; Matuyama age).**
* **QTa** — [Mount Trumbull quad](https://pubs.usgs.gov/imap/i2766/) only: under “SURFICIAL DEPOSITS”, **Old alluvium (Pleistocene and Pliocene)**.

I’ll go see if I can find descriptions of each in the supplementary materials for each quad, and see if I can get a pull request put together. This is fun, and is making me familiar with several parts of the map I hadn’t explored yet.

**Comment by brandon-rhodes** [comment]
The above pull request adds the formations from your list ­— except for the `Trm` polygon which I believe is supposed to be `^m`. Just for fun I'll now go look for the `Unknown` formations that were not in your list.
