### ISSUE TITLE
Mislabeled Esplanade polygon

### ISSUE THREAD

**Issue by rclark** [rclark/grand-canyon-geology#27]
<img width="284" alt="Screen Shot 2020-12-21 at 5 23 54 PM" src="https://user-images.githubusercontent.com/515424/102834457-f2159700-43a8-11eb-9df8-b95de4df9289.png">

This a single polygon east of the Bright Angel Trail that's mislabeled as `Mr` when it should be `Pe`. Makes it look like there's a suite of secret faults duplicating the Redwall in the section.

In a big geojson file of polygons with no unique identifiers, its a little hard to track this one down and fix it. Time to break open qgis...

**Comment by rclark** [comment]
<img width="557" alt="Screen Shot 2022-05-21 at 12 29 53 PM" src="https://user-images.githubusercontent.com/515424/169666540-179f2466-cce8-4a08-9d2d-3f1444e83229.png">

Fixed!

**Comment by brandon-rhodes** [comment]
Good catch—and, wow, that's a very long and very winding polygon. 🙂

**Comment by rclark** [comment]
The really hard part about these kinds of changes is that there's no good software for selecting & manipulating attributes in GeoJSON files this big. I had to install QGIS, where every pan/zoom/click means waiting at least a minute for the map to redraw.
