### ISSUE TITLE
Citing grand-canyon-geology

### ISSUE THREAD

**Issue by fmcnab** [rclark/grand-canyon-geology#29]
Hello!

Apologies for getting in touch like this - I don't have an 'issue' as such, but couldn't see a simpler way of getting in touch. I am a geologist based at the German Research Centre for Geosciences, and am currently preparing a paper for publication in GSA Bulletin in which I made use of the data you provided here in several figures. I just want to make sure I cite everything properly. I will certainly reference the original USGS maps you list, but would also like to point people towards this excellent resource and acknowledge the effort that went into creating it. As such I am planning to include a line like the following in the relevant figure caption:

"Outcrop distributions based upon Billingsley (2000), Billingsley and Wellmeyer (2003) and Billingsley et al. (2006a), Billingsley et al., (2006b), Billingsley et al., (2007), Billingsley et al. (2012) and available from http://rclark.github.io/grand-canyon-geology (courtesy of R. Clark)."

Before finalising the paper I thought it would be worth checking with you if this was ok and whether there is anything I might be missing? If you have any questions, do let me know. Thank you for putting together and maintaining such a great resource!

Best wishes,

Fergus McNab

p.s. if you would rather discuss by email, you can find my details here: https://www.gfz-potsdam.de/en/staff/fergus-mcnab/sec46/

**Comment by rclark** [comment]
Hi Fergus -- sorry for the delay. I appreciate your desire to draw attention to this site. The citation that you proposed sounds great to me.
