### ISSUE TITLE
Map Purchase

### ISSUE THREAD

**Issue by Cmactak** [rclark/grand-canyon-geology#31]
This is the most beautiful map I've ever seen of the Geology of the Grand Canyon. Is it still in print and available? I could not find it on the USGS website.  Thank you.

https://rclark.github.io/grand-canyon-geology/#11/36.1495/-111.9874

**Comment by rclark** [comment]
Thanks for the compliment! This map was developed specifically for the website, so what you see there has never actually been a printed product.

However, the data behind the website is compiled from a number of USGS publications [which are listed here in the readme](https://github.com/rclark/grand-canyon-geology#grand-canyon-geology). You can find PDF files there if you follow the links.
