### ISSUE TITLE
Map layers are not loading

### ISSUE THREAD

**Issue by aazaff** [rclark/grand-canyon-geology#35]
hey, I noticed the layers are not actually loading - even on the staging branch. Do you have any idea what is up?

**Comment by brandon-rhodes** [comment]
For what it's worth, I can confirm that I see the same thing; here's what the JS console looks like:

![image](https://github.com/rclark/grand-canyon-geology/assets/166162/2ddc97eb-2728-4146-b77f-5d7ddc80b43b)

**Comment by royhirshkowitz** [comment]
Confirmed-- unable to load the map on any browser for a week or so.

**Comment by rclark** [comment]
Fixed! 

Sorry, this was a billing issue, and I was out in canyon country. Hopefully a photo of Navajo Mountain can help make up for it.

![IMG_2547](https://github.com/rclark/grand-canyon-geology/assets/515424/f0009225-a988-4e73-9cb8-bb86562a1ece)

**Comment by brandon-rhodes** [comment]
That's a wonderful photo! The Reflection Canyon Trail? How was it? I was able to hike Coyote Gulch, Fence, and Fortymile last year, but haven't yet made it to any of the canyons down at the very south end of Hole in the Rock road!

**Comment by aazaff** [comment]
Sorry you have to pay for it out of pocket. Do you want to switch from mapbox to arconline tiles? We can do free vector tiles through UA.

**Comment by rclark** [comment]
> That's a wonderful photo!

Yes, that's the trail towards Reflection Canyon. The Grand Staircase NM is my happy place ❤️

> Sorry you have to pay for it out of pocket

Thanks, but it is very affordable.
